name: theStack - Todo
services:
  postgres:
    image: postgres:16-alpine
    ports:
      - ${DB_PORT}:5432
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
    volumes:
      - postgres:/var/lib/postgresql/data
  
  redis:
    image: redis:7-alpine
    command: redis-server --requirepass ${QUEUE_REDIS_PASSWORD}
    ports:
      - ${QUEUE_REDIS_PORT}:6379
    volumes:
      - redis:/data

volumes:
  postgres:
  redis: